name: GEFfy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - matplotlib=3.5.0
  - pandas=1.4.2
  - numpy=1.20.3
  - scipy=1.7.3
  - seaborn=0.11.2
  - flit=3.6.0
  - ipywidgets=7.6.3
  - scikit-learn=1.0.2